name: Big Rick Stuart
favicon: null
layout_spectrum: 0.24169
typography_spectrum: 0.6612805670592934
title: Hardly Strictly Wine Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73569106-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201c1e'
    - '#505483'
    - '#ffffff'
    - '#8a8989'
    - '#23ad51'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
