typography_spectrum: 0.522083232877776
color:
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
  brandStrength: 0.16730519570410252
  lightness: 0.5150991254486144
  saturation: 0.13571509579196572
  rhythmicContrast: 0.023124723695218563
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2708090110681951
analytics:
  google: UA-73569106-1
  facebook: null
  twitter: null
author:
  name: Big Rick
  email: rick@KVYN.com
  url: 'http://www.993thevine.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/deca59fd-264e-430f-a765-16ed607dc546.png
name: Hardly Strictly Wine Blog
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 99.3 The Vine Napa's Sauvignon Rock
    url: 'http://www.993thevine.com'
    type: external
favicon: null
title: 99.3 The Vine Hardly Strictly Wine Blog
content: []
description: wine food travel Napa and more
purpose:
  - type: contact
    url: 'mailto:rick@kvyn.com'
    label: email
github: true
