typography_spectrum: 0.6612805670592934
color:
  brandColors:
    - '#201c1e'
    - '#505483'
    - '#ffffff'
    - '#8a8989'
    - '#23ad51'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24169
analytics:
  google: UA-73569106-1
  facebook: null
  twitter: null
name: Big Rick Stuart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hardly Strictly Wine Blog
description: from 99.3 The Vine Napa
purpose: []
